service: SwapiAPI
frameworkVersion: '3'
useDotenv: true

custom:
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  SWAPI_TABLE_NAME: swapi-register-${self:custom.stage}

package:
  patterns:
    - '!package-lock.json'
    - '!package.json'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20200924
  region: ${self:custom.region}
  environment: ${self:custom}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

plugins:
  - serverless-plugin-typescript

functions:
  # Endpoints relacionados a People en Swapi
  getTranslatePeople:
    handler: src/functions/people/functions/getTranslatePeople.handler
    events:
      - http:
          path: swapi/people/{id}
          method: get
          caching:
            enabled: true

  saveTranslatePeople:
    handler: src/functions/people/functions/saveTranslatePeople.handler
    events:
      - http:
          path: swapi/people/{id}
          method: post
          caching:
            enabled: true
  getPersona:
    handler: src/functions/people/functions/getPersona.handler
    events:
      - http:
          path: swapi/persona/{id}
          method: get
          caching:
            enabled: true
  getAllPersonas:
    handler: src/functions/people/functions/getAllPersonas.handler
    events:
      - http:
          path: swapi/personas
          method: get
          caching:
            enabled: true

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.SWAPI_TABLE_NAME}
