service: SwapiAPI
frameworkVersion: '3'
useDotenv: true

custom:
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  SWAPI_PERSONAS_TABLE_NAME: swapi-personas-${self:custom.stage}
  SWAPI_PLANETAS_TABLE_NAME: swapi-planetas-${self:custom.stage}

package:
  patterns:
    - '!package-lock.json'
    - '!package.json'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20200924
  region: ${self:custom.region}
  environment: ${self:custom}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

plugins:
  - serverless-plugin-typescript

functions:
  # Endpoints relacionados a People en Swapi
  getTranslatePeople:
    handler: src/functions/people/functions/getTranslatePeople.handler
    events:
      - http:
          path: swapi/people/{id}
          method: get
          caching:
            enabled: true

  saveTranslatePeople:
    handler: src/functions/people/functions/saveTranslatePeople.handler
    events:
      - http:
          path: swapi/people/{id}
          method: post
          caching:
            enabled: true
  getPersona:
    handler: src/functions/people/functions/getPersona.handler
    events:
      - http:
          path: swapi/persona/{id}
          method: get
          caching:
            enabled: true
  getAllPersonas:
    handler: src/functions/people/functions/getAllPersonas.handler
    events:
      - http:
          path: swapi/personas
          method: get
          caching:
            enabled: true

  # Endpoints relacionados a Planet de swapi
  # getTranslatePlanet:
  #   handler: src/functions/planet/functions/getTranslatePlanet.handler
  #   events:
  #     - http:
  #         path: swapi/planet/{id}
  #         method: get
  #         caching:
  #           enabled: true

  saveTranslatePlanet:
    handler: src/functions/planet/functions/saveTranslatePlanet.handler
    events:
      - http:
          path: swapi/planet/{id}
          method: post
          caching:
            enabled: true
  getPlaneta:
    handler: src/functions/planet/functions/getPlaneta.handler
    events:
      - http:
          path: swapi/planeta/{id}
          method: get
          caching:
            enabled: true
  # getAllPlanets:
  #   handler: src/functions/planet/functions/getAllPlanets.handler
  #   events:
  #     - http:
  #         path: swapi/planets
  #         method: get
  #         caching:
  #           enabled: true

resources:
  Resources:
    DynamoDbPersonaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.SWAPI_PERSONAS_TABLE_NAME}

    DynamoDbPlanetaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.SWAPI_PLANETAS_TABLE_NAME}
